name: melody
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.18
  audio_service: ^0.18.3
  google_sign_in: ^5.2.3
  cached_network_image: ^3.2.0
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  lottie: ^1.2.1
  dio: ^4.0.4
  rxdart: ^0.27.3
  url_launcher: ^6.0.18
  path_provider: ^2.0.8
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.0.0
  internet_connection_checker: ^0.0.1+3
  provider: ^6.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/anim/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
